Newly implemented items
valence-smp/resource-pack pull request #46
Opened 2022-11-10 05:17 UTC by Bats202

This has a trophie for the event

2022-11-11 18:58 UTC, Starmism requested changes
See notes. Make sure we have credits for all model files.

2022-11-11 18:58 UTC, Starmism commented on Dev Pack/assets/minecraft/models/item/stick.json
> +		  {"predicate": {"custom_model_data":15040}, "model": "valence:weapon/magic_staff/ms_optic_purple"}
What's going on here?

2022-11-11 18:58 UTC, Starmism commented on Dev Pack/assets/minecraft/models/item/shield.json
> +      {"predicate": {"custom_model_data": 10512}, "model": "valence:armor/shield/rotten_tower_shield"},
Any particular reason to move the rotten tower shield instead of the shield of stendahl? Based on what kooky said, the shield of stendahl is the one not working.

2022-11-11 18:58 UTC, Starmism commented on Dev Pack/assets/valence/models/weapon/magic_staff/ms_moon_blue.json
> +	"credit": "Made with Blockbench",
By whom?

2022-11-11 18:58 UTC, Starmism commented on Dev Pack/assets/valence/models/weapon/magic_staff/ms_moon_green.json
> +	"credit": "Made with Blockbench",
No accreditation for like half of these new models.

2022-11-21 20:12 UTC, RedNinja25 commented on Dev Pack/assets/valence/models/weapon/magic_staff/ms_moon_green.json
> +	"credit": "Made with Blockbench",
Majority of the staffs are purchased

2022-11-21 20:13 UTC, Starmism commented on Dev Pack/assets/valence/models/weapon/magic_staff/ms_moon_green.json
> +	"credit": "Made with Blockbench",
They still should probably state where purchased from or the author of that, but I don't really care that much.

2022-11-25 00:32 UTC, Gearp0wer approved these changes

2022-11-25 00:55 UTC, Gearp0wer commented on Dev Pack/assets/valence/models/weapon/magic_staff/ms_moon_blue.json
> +	"credit": "Made with Blockbench",
It was bought as part of a pack, still should credit for use by valence but w/e

2022-11-25 03:49 UTC, merged