arcane battery
valence-smp/resource-pack pull request #57
Opened 2023-01-15 18:45 UTC by Criticalmage113

Items needed for Arcane Battery

2023-01-15 18:56 UTC, Gearp0wer commented
side note, I feel like more than star and I should be able to approve these but idk, thats just me

2023-01-15 22:03 UTC, Starmism requested changes

2023-01-15 22:03 UTC, Starmism commented on Dev Pack/assets/minecraft/models/item/heart_of_the_sea.json
> +	{"predicate": { "custom_model_data": 11007}, "model": "valence:misc/the_godseed"}
These should also be unindented

2023-01-15 22:03 UTC, Starmism commented on Dev Pack/assets/minecraft/models/item/book.json
> +	  {"predicate": {"custom_model_data": 11002}, "model": "valence:weapon/magic/maldores_spellbook"},
This should be unindented and should have an empty line after it to signify the jump from 11000 to 14000

2023-01-15 22:03 UTC, Starmism commented on Dev Pack/assets/minecraft/models/item/stick.json
> +	  {"predicate": {"custom_model_data": 11050}, "model": "valence:weapon/magic/maldore_wand2_1"},
Should be unindented

2023-01-18 22:54 UTC, Starmism approved these changes

2023-01-18 22:55 UTC, merged